row=324;  col=324;
raw_image='raw\sample4.raw';
fin=fopen(raw_image,'r');
I=fread(fin,row*col,'uint8=>uint8');
fclose(fin);
S1=reshape(I,row,col);
S1=S1';
%k=figure,imshow(S1);
%corners1 = detectFASTFeatures(S1);
%figure,imshow(S1); hold on;
%plot(corners1.selectStrongest(50));
S1_HE=histeq(S1);
%figure,imshow(S1_HE);
corners1_HE = detectFASTFeatures(S1_HE);
figure,imshow(S1_HE, 'Border','tight'); hold on;
plot(corners1_HE.selectStrongest(50));

raw_image='..\raw\sample5.raw';
fin=fopen(raw_image,'r');
I=fread(fin,row*col,'uint8=>uint8');
fclose(fin);
S2=reshape(I,row,col);
S2=S2';
%k=figure,imshow(S2);
%corners2 = detectFASTFeatures(S2);
%figure,imshow(S2); hold on;
%plot(corners2.selectStrongest(30));
S2_HE=histeq(S2);
%figure,imshow(S2_HE);
corners2_HE = detectFASTFeatures(S2_HE);
figure,imshow(S2_HE,'Border','tight'); hold on;
plot(corners2_HE.selectStrongest(50));

raw_image='..\raw\sample6.raw';
fin=fopen(raw_image,'r');
I=fread(fin,row*col,'uint8=>uint8');
fclose(fin);
S3=reshape(I,row,col);
S3=S3';
%k=figure,imshow(S3);
%corners3 = detectFASTFeatures(S3);
%figure,imshow(S3); hold on;
%plot(corners3.selectStrongest(30));
S3_HE=histeq(S3);
%figure,imshow(S3_HE);
corners3_HE = detectFASTFeatures(S3_HE);
figure,imshow(S3_HE,'Border','tight'); hold on;
plot(corners3_HE.selectStrongest(50));

raw_image='..\raw\sample7.raw';
fin=fopen(raw_image,'r');
I=fread(fin,row*col,'uint8=>uint8');
fclose(fin);
S4=reshape(I,row,col);
S4=S4';
%k=figure,imshow(S4);
%corners4 = detectFASTFeatures(S4);
%figure,imshow(S4); hold on;
%plot(corners4.selectStrongest(30));
S4_HE=histeq(S4);
%figure,imshow(S4_HE);
corners4_HE = detectFASTFeatures(S4_HE);
figure,imshow(S4_HE,'Border','tight'); hold on;
plot(corners4_HE.selectStrongest(50));
